joint_limits:
  rightArm_arm_2_joint:
    has_velocity_limits: true
    max_velocity: 2.26892802759
    has_acceleration_limits: true
    max_acceleration: 0.453785605518
  leftGripper_thumb_2_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
  leftGripper_thumb_3_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
  rightGripper_finger_12_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
  rightGripper_finger_13_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
  rightGripper_thumb_3_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
  rightArm_arm_0_joint:
    has_velocity_limits: true
    max_velocity: 1.91986217719
    has_acceleration_limits: true
    max_acceleration: 0.383972435438
  rightArm_arm_1_joint:
    has_velocity_limits: true
    max_velocity: 1.91986217719
    has_acceleration_limits: true
    max_acceleration: 0.383972435438
  leftArm_arm_4_joint:
    has_velocity_limits: true
    max_velocity: 2.26892802759
    has_acceleration_limits: true
    max_acceleration: 0.453785605518
  rightGripper_thumb_2_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
  leftGripper_finger_22_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
  rightGripper_finger_23_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
  rightGripper_finger_22_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
  leftArm_arm_1_joint:
    has_velocity_limits: true
    max_velocity: 1.91986217719
    has_acceleration_limits: true
    max_acceleration: 0.383972435438
  leftArm_arm_2_joint:
    has_velocity_limits: true
    max_velocity: 2.26892802759
    has_acceleration_limits: true
    max_acceleration: 0.453785605518
  leftArm_arm_5_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: true
    max_acceleration: 0.628318530718
  leftArm_arm_6_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: true
    max_acceleration: 0.628318530718
  leftArm_arm_3_joint:
    has_velocity_limits: true
    max_velocity: 2.26892802759
    has_acceleration_limits: true
    max_acceleration: 0.453785605518
  leftGripper_finger_12_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
  leftGripper_finger_13_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
  rightArm_arm_6_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: true
    max_acceleration: 0.628318530718
  rightArm_arm_3_joint:
    has_velocity_limits: true
    max_velocity: 2.26892802759
    has_acceleration_limits: true
    max_acceleration: 0.453785605518
  rightGripper_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
  leftGripper_finger_23_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
  leftGripper_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 5
    has_acceleration_limits: true
    max_acceleration: 1
  leftArm_arm_0_joint:
    has_velocity_limits: true
    max_velocity: 1.91986217719
    has_acceleration_limits: true
    max_acceleration: 0.383972435438
  rightArm_arm_5_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: true
    max_acceleration: 0.628318530718
  rightArm_arm_4_joint:
    has_velocity_limits: true
    max_velocity: 2.26892802759
    has_acceleration_limits: true
    max_acceleration: 0.453785605518