joint_limits:
  right_arm_2_joint:
    has_velocity_limits: true
    max_velocity: 2.26892802759
    has_acceleration_limits: true
    max_acceleration: 0.453785605518
  right_arm_0_joint:
    has_velocity_limits: true
    max_velocity: 1.91986217719
    has_acceleration_limits: true
    max_acceleration: 0.383972435438
  right_arm_4_joint:
    has_velocity_limits: true
    max_velocity: 2.26892802759
    has_acceleration_limits: true
    max_acceleration: 0.453785605518
  right_arm_3_joint:
    has_velocity_limits: true
    max_velocity: 2.26892802759
    has_acceleration_limits: true
    max_acceleration: 0.453785605518
  right_arm_5_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: true
    max_acceleration: 0.628318530718
  right_arm_6_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: true
    max_acceleration: 0.628318530718
  right_arm_1_joint:
    has_velocity_limits: true
    max_velocity: 1.91986217719
    has_acceleration_limits: true
    max_acceleration: 0.383972435438