sensors: 
 - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
   point_cloud_topic: /pose_estimation_uibk/reconstructed_scene
   #point_cloud_topic: /camera/depth_registered/points
   max_range: 3.0
   padding_offset: 0
   padding_scale: 1
   point_subsample: 1
   filtered_cloud_topic: output_cloud